// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shipping.API.Data;

#nullable disable

namespace Shipping.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501144613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Shipping.API.Data.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 1,
                            Status = 2,
                            TrackingNumber = "TRK-100001"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 2,
                            Status = 1,
                            TrackingNumber = "TRK-100002"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 3,
                            Status = 0,
                            TrackingNumber = "TRK-100003"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
