// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.API.Data;

#nullable disable

namespace Product.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501083336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Product.API.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop Pro 15",
                            Price = 1299.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 3,
                            Name = "USB-C Hub",
                            Price = 49.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 4,
                            Name = "4K Monitor",
                            Price = 599.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 6,
                            Name = "Webcam HD",
                            Price = 69.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 7,
                            Name = "Noise Cancelling Headphones",
                            Price = 249.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 8,
                            Name = "Phone Stand",
                            Price = 19.99m,
                            StockQuantity = 300
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
