// <auto-generated />
using System;
using Analytics.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Analytics.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501145834_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Analytics.API.Data.Models.ClickEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ClickEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            EventType = "view",
                            ProductId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 9, 10, 0, 0, DateTimeKind.Utc),
                            EventType = "view",
                            ProductId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventType = "view",
                            ProductId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 10, 15, 0, 0, DateTimeKind.Utc),
                            EventType = "view",
                            ProductId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            EventType = "view",
                            ProductId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 2, 8, 30, 0, 0, DateTimeKind.Utc),
                            EventType = "add_cart",
                            ProductId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            EventType = "add_cart",
                            ProductId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            EventType = "view",
                            ProductId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 3, 11, 20, 0, 0, DateTimeKind.Utc),
                            EventType = "add_cart",
                            ProductId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            EventType = "view",
                            ProductId = 6,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Analytics.API.Data.Models.ConversionStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConversionStats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            OrderId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 2, 9, 45, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            OrderId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 3, 13, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            OrderId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
