// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment.API.Data;

#nullable disable

namespace Payment.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501142642_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Payment.API.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1299.99m,
                            CreatedAt = new DateTime(2026, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 29.99m,
                            CreatedAt = new DateTime(2026, 4, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 49.99m,
                            CreatedAt = new DateTime(2026, 4, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            OrderId = 3,
                            Status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
